# Site settings
email: chris.ferrer03@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-83531470-9

# SEO settings
title: Chris Ferrer's Blog
description: Chris writes about Product, Music, and Food. He's a product manager at BlackRock helping people with automated investing for the future.
url: "chrisferrer.me"
twitter_username: verbosesilence
default_img: https://drive.google.com/file/d/18zgyJk579Ft4b3qJi0iD7lVXzDPN6UK1/view?usp=sharing

# Profile settings
name: Chris Ferrer
profile_img: https://drive.google.com/file/d/18zgyJk579Ft4b3qJi0iD7lVXzDPN6UK1/view?usp=sharing
profile: Chris grew up in Hawaii, and now lives in chilly San Francisco. A philosopher by trade, and a product manager by day at FutureAdvisor (a Blackrock company). He moonlights as an ahi poke chef and can be found watching the Chelsea Football Club weekends at the crack of dawn due to an unfortunate time difference from England.
social:
  github: https://github.com/chrisferrer
  linkedin: https://www.linkedin.com/in/chris-ferrer
  twitter: https://twitter.com/verbosesilence
  soundcloud: https://soundcloud.com/chris_ferrer
  instagram: https://www.instagram.com/chrisusesinstgram/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed
